### ISSUE TITLE
Support for dark theme

### ISSUE THREAD

**Issue by georgesamy** [glassmonkey/php-playground#120]
[feature-request] 

Adding a toggle that switches between light and dark themes in the frontend

If approved I can provide a PR

**Comment by glassmonkey** [comment]
@georgesamy 

Thanks for the feature request. I've been aware of its importance but haven't had the chance to tackle it yet.

I welcome your Pull Request and appreciate your initiative.
 Please note that we might need to make some adjustments for compatibility with existing features.

**Comment by glassmonkey** [comment]
done
