### ISSUE TITLE
togglable real-time compiling

### ISSUE THREAD

**Issue by syddiqua** [glassmonkey/php-playground#158]
Hello! It's a very useful tool, I really like it. My only slightly annoying issue is that it throws an error in the output after typing just the first few characters. It would be great to have a switch to toggle the real-time translation, and if it's turned off, a RUN button could generate the output of the current code.

**Comment by glassmonkey** [comment]
I apologize for the delayed response. The application is based on the concept of real-time interaction; therefore,I do not intend to accept your proposal.
